create table questions (
    id bigint generated by default as identity primary key,
    section varchar(255) not null,
    topic varchar(255) not null,
    type varchar(50) not null,
    text varchar(2000) not null,
    explanation varchar(4000),
    translation varchar(4000),
    difficulty varchar(50) not null,
    source_type varchar(50) not null,
    active boolean not null
);

create table answer_options (
    id bigint generated by default as identity primary key,
    text varchar(1000) not null,
    correct boolean not null,
    question_id bigint not null,
    constraint fk_answer_option_question
        foreign key (question_id) references questions(id)
);

create table exam_sessions (
    id bigint generated by default as identity primary key,
    mode varchar(50) not null,
    started_at timestamp not null,
    finished_at timestamp,
    total_questions integer not null,
    correct_answers integer,
    completed boolean not null
);

create table user_answers (
    id bigint generated by default as identity primary key,
    exam_session_id bigint not null,
    question_id bigint not null,
    selected_option_id bigint not null,
    correct boolean not null,
    constraint fk_user_answer_exam_session
        foreign key (exam_session_id) references exam_sessions(id),
    constraint fk_user_answer_question
        foreign key (question_id) references questions(id),
    constraint fk_user_answer_selected_option
        foreign key (selected_option_id) references answer_options(id)
);