create table practical_task (
    id bigint generated by default as identity primary key,
    title varchar(500),
    scenario varchar(5000),
    task varchar(5000),
    sample_approach varchar(5000)
);

create table practical_task_what_to_cover (
    practical_task_id bigint not null,
    what_to_cover varchar(2000),
    constraint fk_practical_task_what_to_cover
        foreign key (practical_task_id) references practical_task(id)
);